### ISSUE TITLE
Build tests

### ISSUE THREAD

**Issue by ocefpaf** [wesleybowman/UTide#10]
UTide needs some test to help developers/contributors evaluate the changes quickly.

**Comment by ocefpaf** [comment]
@wesleybowman I want to create a list of issues, bugs, and expected behavior to start writing some tests.  For now I have #2 and #3 to start with.  If @saulomeirelles could provide a [sscce](http://sscce.org/) with those issues it will help a lot.  (I have zero experience running UTide.)

PS1: The sscce can be in Matlab and with fake data.  We want to be sure we get the same result as MatlabTM :grimacing: 

PS2: Bonus points if the Matlab examples are written in a [notebook](https://pypi.python.org/pypi/matlab_kernel) hosted as [gists](https://gist.github.com/) visible on nbviewer. :smiling_imp:

**Comment by wesleybowman** [comment]
Ok, I have some test that I ran when I was creating it. It would run the python for a randomly generated data set, then save the results and then run the matlab and save the results, and then compare the two results. I did not know you could run matlab in Ipython, that's pretty neat. I will try to get your the scripts later today. I will probably just send them in an email, because they were a little confusing for onlookers to see.

**Comment by ocefpaf** [comment]
Great.  I will see if I can organize them as a test suite.

PS: If UTide works with octave we can try to run something similar to what I did for seawater:

https://github.com/ocefpaf/python-seawater/blob/master/seawater/test/test_result_comparison.py

I run both Matlab (via octave) and python version and compare the results.

**Comment by saulomeirelles** [comment]
Hi guys, really sorry for the late answer. I' ve been busy with other
things for few months and did not have time to look at the UTide issues. I
am abroad now with limited access to my dataset. In early March I will have
time to come back to you guys again. Cheers,

**Comment by ocefpaf** [comment]
There is room for improvement, but this task is complete. Closing the issue.

**Comment by poidl** [comment]
> I run both Matlab (via octave) and python version and compare the results.

This is an old issue but very view results come up when searching for 'utide octave', so I thought it may still be seen by people  attempting to compare the python code (great project!) with the Matlab code running in Octave. This is actually a note on octave I guess, but useful for people who want to do testing of the python version and have no Matlab. 

I  noticed a difference between Octave and Python in the predictions using the default parameters (SNR min = 2). It turned out that Octave yielded different confidence intervals than ucode python. After hours of bug searching I found that in `ut_solv.m` 

```
[Puu1s,allfrq] = pwelch(real(e),hn,0,nt);
```

yields a different frequency vector in Octave than (apparently looking at [1] and Dan Codiga's code) Matlab, which yields 'normalized frequency vector' that Dan later converts to cph. This conversion is apparently no necessary in Octave, at least in version  6.4.0. Note a related comment in the Octave mailing list [2]

Thanks for the great python translation!

[1] https://www.mathworks.com/help/signal/ref/pwelch.html#d124e146263
[2] https://savannah.gnu.org/bugs/index.php#comment26
